import { MiniGameRegistryKey } from '../games';
import { LevelData } from '../types';

export const resolveMiniGameRegistryKey = (level: LevelData): MiniGameRegistryKey | null => {
  switch (level.gameType) {
    case 'WORD_WARDEN':
      return 'WordWardenGame';
    case 'TENSE_TOWER':
      return 'TenseTowerGame';
    case 'CLAUSE_KEEP':
      return 'ClauseKeepGame';
    case 'CONJUNCTION_CROSSING':
      return 'ConjunctionCrossingGame';
    case 'GRAMMAR_GUARD':
      return 'GrammarGuardGame';
    case 'COMMA_CANNON':
      return 'CommaCannonGame';
    case 'APOSTROPHE_OUTLAWS':
      return 'ApostropheOutlawsGame';
    case 'PUNCTUATION_PATROL':
      return 'PunctuationPatrolGame';
    case 'STRONGHOLD_SPRINT':
      return 'StrongholdSprintGame';
    case 'PREFIX_PATROL':
      return 'PrefixPatrolGame';
    case 'FORGE_OF_SUFFIXES':
      return 'ForgeOfSuffixesGame';
    case 'SPELLING_FORGE':
      return 'SpellingForgeGame';
    case 'HALL_OF_ECHOES':
      return 'HallOfEchoesGame';
    case 'PATTERN_TRIALS':
      return 'PatternTrialsGame';
    case 'WORD_MORPH':
      return 'WordMorphGame';
    case 'HOMOPHONE_HUNT':
      return 'HomophoneHuntGame';
    case 'SUFFIX_SIEGE':
      return 'SuffixSiegeGame';
    case 'SENTENCE_SMITH':
      return 'SentenceSmithGame';
    case 'SENTENCE_SHIFT':
      return 'SentenceShiftGame';
    case 'BLADE_REFINER':
      return 'BladeRefinerGame';
    case 'POWER_INFUSION':
      return 'PowerInfusionGame';
    case 'FORGE_REPAIR':
      return 'ForgeRepairGame';
    case 'PARAGRAPH_PATCH':
      return 'ParagraphPatchGame';
    case 'CONNECTIVE_CRAFTER':
      return 'ConnectiveCrafterGame';
    case 'WORD_WIZARD':
      return 'WordWizardGame';
    case 'MEANING_MINES':
      return 'MeaningMinesGame';
    case 'SYNONYM_SIEGE':
      return 'SynonymSiegeGame';
    case 'WORD_SENSE':
      return 'WordSenseGame';
    case 'TWIN_WORDS_TRIAL':
      return 'TwinWordsTrialGame';
    case 'ANTONYM_AMBUSH':
      return 'AntonymAmbushGame';
    case 'TONE_TRADER':
      return 'ToneTraderGame';
    case 'MEANING_MATCH':
      return 'MeaningMatchGame';
    case 'RETRIEVAL_RAPIDS':
      return 'RetrievalRapidsGame';
    case 'INFERENCE_ISLE':
      return 'InferenceIsleGame';
    case 'EVIDENCE_EXPLORER':
      return 'EvidenceExplorerGame';
    case 'SEQUENCE_STREAM':
      return 'SequenceStreamGame';
    case 'AUTHOR_INTENT':
      return 'AuthorIntentGame';
    case 'SUMMARY_SELECT':
      return 'SummarySelectGame';
    case 'EVIDENCE_CHAIN':
      return 'EvidenceChainGame';
    case 'PASSAGE_QUEST':
      return 'PassageQuestGame';
    case 'EVIDENCE_HIGHLIGHT':
      return 'EvidenceHighlightGame';
    case 'TWIN_TICK_TRIAL':
      return 'TwinTickTrialGame';
    case 'RULE_BREAKER':
      return 'RuleBreakerGame';
    case 'BEST_ANSWER_QUEST':
      return 'BestAnswerQuestGame';
    case 'MIXED_MASTERY':
      return 'MixedMasteryGame';
    case 'LEGENDS_CHALLENGE':
      return 'LegendsChallengeGame';
    case 'READING_RESCUE':
      return 'ReadingRescueGame';
    case 'GRAMMAR_GAUNTLET':
      return 'GrammarGauntletGame';
    case 'WORDSMITH_TRIALS':
      return 'WordsmithTrialsGame';
    case 'SCHOLARS_SUMMIT':
    case 'INFERENCE_INVADERS':
    case 'RETRIEVAL_RAID':
    case 'LOGIC_LADDER':
    case 'EDITORS_TRIAL':
      return 'EnglishStubGame';
    default:
      return null;
  }
};

