import { MiniGameType } from './types';

export const CANONICAL_GAME_LABELS: Partial<Record<MiniGameType, string>> = {
  potion_pour: 'Potion Panic',
  cloud_collapse: 'Crystal Match',
  logic_sort: 'Logic Sort',
  matrix_match: 'SATs Paper 3',
  take_out_rush: 'Take-Out Rush',
  fraction_match: 'Crystal Match',
  crystal_core: 'SATs Paper 1',
  prime_pop: 'Prime Pop',
  angle_arena: 'Angle Arena',
  polygon_palace: 'Polygon Palace',
  data_dungeon: 'Data Dungeon',
  monster_market: 'Monster Market',
  tower_of_factors: 'Factor Forge',
  measurement_forge: 'Conversion Canyon',
  timekeeper_temple: 'Chrono Dash: Time Trial',
  ratio_rapids: 'Ratio Racer',
  remainder_run: 'Remainder Run',
  place_value_peaks: 'Decimal Sniper',
  calculation_clash: 'Calculation Cup',
  coordinate_quest: 'Coordinates Quest',
  transform_temple: 'Rotation Station',
  mirror_gate: 'SATs Paper 2',
  scale_safari: 'Scale Builder',
  scales_of_the_sun: 'Scale Master',
  graph_grabber: 'Graph Grabber',
  observatory_overload: 'Data Observatory',
  mean_machine: 'Mean Machine',
  equation_grove: 'Order Ops Arena',
  rule_runner: 'Rule Runner',
  percent_power: 'Percent Power',
  area_architect: 'Area Architect',
  ratio_fractions: 'Ratio Racer',
  formula_forge: 'Formula Forge',
  unit_mixer: 'Lava Path',
  change_counter: 'Monster Market',
  reasoning_quest: 'Reasoning Quest',
  WORD_WARDEN: 'Word Warden',
  TENSE_TOWER: 'Tense Tower',
  CLAUSE_KEEP: 'Clause Keep',
  CONJUNCTION_CROSSING: 'Conjunction Crossing',
  GRAMMAR_GUARD: 'Grammar Guard',
  COMMA_CANNON: 'Comma Cannon',
  APOSTROPHE_OUTLAWS: 'Apostrophe Outlaws',
  PUNCTUATION_PATROL: 'Punctuation Patrol',
  STRONGHOLD_SPRINT: 'Stronghold Sprint',
  PREFIX_PATROL: 'Prefix Patrol',
  FORGE_OF_SUFFIXES: 'Forge of Suffixes',
  HALL_OF_ECHOES: 'Hall of Echoes',
  SPELLING_FORGE: 'Spelling Forge',
  PATTERN_TRIALS: 'Pattern Trials',
  WORD_MORPH: 'Word Morph',
  HOMOPHONE_HUNT: 'Homophone Hunt',
  SUFFIX_SIEGE: 'Suffix Siege',
  SENTENCE_SMITH: 'Sentence Smith',
  SENTENCE_SHIFT: 'Sentence Shift',
  BLADE_REFINER: 'Blade Refiner',
  POWER_INFUSION: 'Power Infusion',
  FORGE_REPAIR: 'Forge Repair',
  PARAGRAPH_PATCH: 'Paragraph Patch',
  CONNECTIVE_CRAFTER: 'Connective Crafter',
  WORD_SENSE: 'Word Sense',
  TWIN_WORDS_TRIAL: 'Twin Words Trial',
  ANTONYM_AMBUSH: 'Antonym Ambush',
  TONE_TRADER: 'Tone Trader',
  MEANING_MATCH: 'Meaning Match',
  WORD_WIZARD: 'Word Wizard',
  MEANING_MINES: 'Meaning Mines',
  SYNONYM_SIEGE: 'Synonym Siege',
  EVIDENCE_HIGHLIGHT: 'Evidence Highlight',
  RETRIEVAL_RAPIDS: 'Retrieval Rapids',
  INFERENCE_ISLE: 'Inference Isle',
  EVIDENCE_EXPLORER: 'Evidence Explorer',
  SEQUENCE_STREAM: 'Sequence Stream',
  AUTHOR_INTENT: 'Author Intent',
  SUMMARY_SELECT: 'Summary Select',
  EVIDENCE_CHAIN: 'Evidence Chain',
  PASSAGE_QUEST: 'Passage Quest',
  INFERENCE_INVADERS: 'Inference Invaders',
  RETRIEVAL_RAID: 'Retrieval Raid',
  LOGIC_LADDER: 'Logic Ladder',
  TWIN_TICK_TRIAL: 'Twin Tick Trial',
  RULE_BREAKER: 'Rule Breaker',
  BEST_ANSWER_QUEST: 'Best Answer Quest',
  EDITORS_TRIAL: "Editor's Trial",
  MIXED_MASTERY: 'Mixed Mastery',
  LEGENDS_CHALLENGE: 'Legends Challenge',
  READING_RESCUE: 'Reading Rescue',
  GRAMMAR_GAUNTLET: 'Grammar Gauntlet',
  WORDSMITH_TRIALS: 'Wordsmith Trials',
  SCHOLARS_SUMMIT: "Scholar's Summit",
};

export const getCanonicalGameLabel = (gameType?: MiniGameType | null) => (
  gameType ? CANONICAL_GAME_LABELS[gameType] ?? gameType.replace(/_/g, ' ') : ''
);
