import { MiniGameType } from './types';

export const CANONICAL_GAME_LABELS: Partial<Record<MiniGameType, string>> = {
  WORD_WARDEN: 'Word Class Wars',
  TENSE_TOWER: 'Tense Trials',
  CLAUSE_KEEP: 'Clause Crusher',
  CONJUNCTION_CROSSING: 'Conjunction Crossing',
  GRAMMAR_GUARD: 'Grammar Guard',
  COMMA_CANNON: 'Comma Cannon',
  APOSTROPHE_OUTLAWS: 'Apostrophe Outlaws',
  PUNCTUATION_PATROL: 'Punctuation Panic',
  STRONGHOLD_SPRINT: 'Stronghold Sprint',
  PREFIX_PATROL: 'Prefix Patrol',
  FORGE_OF_SUFFIXES: 'Forge of Suffixes',
  HALL_OF_ECHOES: 'Hall of Echoes',
  SPELLING_FORGE: 'Spellbound Forge',
  PATTERN_TRIALS: 'Pattern Trials',
  WORD_MORPH: 'Word Morph',
  HOMOPHONE_HUNT: 'Homophone Hunt',
  SUFFIX_SIEGE: 'Suffix Siege',
  SENTENCE_SMITH: 'Sentence Surgery',
  SENTENCE_SHIFT: 'Sentence Shift',
  BLADE_REFINER: 'Blade Refiner',
  POWER_INFUSION: 'Power Infusion',
  FORGE_REPAIR: 'Forge Repair',
  PARAGRAPH_PATCH: 'Paragraph Patch',
  CONNECTIVE_CRAFTER: 'Connective Crafter',
  WORD_SENSE: 'Word Meaning Woods',
  TWIN_WORDS_TRIAL: 'Twin Words Trial',
  ANTONYM_AMBUSH: 'Antonym Ambush',
  TONE_TRADER: 'Tone Trader',
  MEANING_MATCH: 'Meaning Match',
  WORD_WIZARD: 'Word Wizard',
  MEANING_MINES: 'Meaning Mines',
  SYNONYM_SIEGE: 'Synonym Siege',
  EVIDENCE_HIGHLIGHT: 'Evidence Hunter',
  RETRIEVAL_RAPIDS: 'Retrieval Rapids',
  INFERENCE_ISLE: 'Inference Island',
  EVIDENCE_EXPLORER: 'Evidence Explorer',
  SEQUENCE_STREAM: 'Sequence Stream',
  AUTHOR_INTENT: "Author’s Intent Arena",
  SUMMARY_SELECT: 'Summit Summariser',
  EVIDENCE_CHAIN: 'Evidence Chain',
  PASSAGE_QUEST: 'Passage Quest',
  INFERENCE_INVADERS: 'Inference Invaders',
  RETRIEVAL_RAID: 'Retrieval Raid',
  LOGIC_LADDER: 'Logic Ladder',
  TWIN_TICK_TRIAL: 'Twin Tick Trial',
  RULE_BREAKER: 'Rule Breaker',
  BEST_ANSWER_QUEST: 'Best Answer Quest',
  EDITORS_TRIAL: "Editor's Trial",
  MIXED_MASTERY: 'Mixed Mastery',
  LEGENDS_CHALLENGE: 'Legends Challenge',
  READING_RESCUE: 'Trial of Reading',
  GRAMMAR_GAUNTLET: 'Grammar Gauntlet',
  WORDSMITH_TRIALS: 'Trial of GPS',
  SCHOLARS_SUMMIT: "Scholar's Summit",
};

export const getCanonicalGameLabel = (gameType?: MiniGameType | null) => (
  gameType ? CANONICAL_GAME_LABELS[gameType] ?? gameType.replace(/_/g, ' ') : ''
);
